version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server-app-img
    container_name: server-app
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    ports:
      - '5000:5000'
    env_file:
      - ./server/config/config.env
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client-app-img
    container_name: client-app
    command: yarn start
    stdin_open: true
    ports:
      - '3000:3000'
    depends_on:
      - server
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
